# Generated by Django 6.0.7 on 2026-08-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.CharField(help_text='e.g. "11:00 AM"', max_length=30)),
                ('meet_link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='hub.division')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cert', 'Certificate'), ('email', 'Email Template'), ('general', 'General Rule'), ('dept_rule', 'Department Rule')], max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('PDF', 'PDF'), ('TXT', 'TXT')], default='PDF', max_length=4)),
                ('body', models.TextField(blank=True, help_text='Placeholder content, one line per row')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('department', models.ForeignKey(blank=True, help_text='Only used for Department Rule documents', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_documents', to='hub.department')),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('bkash', models.CharField(blank=True, max_length=30, verbose_name='bKash number')),
                ('salary', models.PositiveIntegerField(help_text='Monthly salary in BDT')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('responsibilities', models.TextField(blank=True, help_text='One responsibility per line')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hub.department')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hub.division')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateField()),
                ('last_renewal', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='hub.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=255)),
                ('points', models.TextField(blank=True, help_text='One discussion point per line')),
                ('absent_employees', models.ManyToManyField(blank=True, related_name='absent_meetings', to='hub.employee')),
                ('divisions', models.ManyToManyField(blank=True, related_name='meetings', to='hub.division')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Interviewing', 'Interviewing'), ('On Hold', 'On Hold')], default='Open', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='hub.department')),
            ],
            options={
                'ordering': ['department__name'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('background', models.CharField(blank=True, max_length=255)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('cv_link', models.URLField(blank=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='candidate_cvs/')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='hub.recruitmentround')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('todo', 'To-Do'), ('progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=10)),
                ('due', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hub.employee')),
            ],
            options={
                'ordering': ['due'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Stored as the 1st of the paid month')),
                ('paid', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='hub.employee')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
