# Generated by Django 6.0.7 on 2026-08-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('selected', 'Selected'), ('not_selected', 'Not Selected')], default='waiting', max_length=15),
        ),
    ]
