# Generated by Django 6.0.7 on 2026-08-03 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='hub.department'),
        ),
        migrations.CreateModel(
            name='DepartmentMonthlyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Stored as the 1st of the month')),
                ('task', models.CharField(max_length=255)),
                ('due_date', models.DateField(help_text="Last date to complete this month's task")),
                ('status', models.CharField(choices=[('due', 'Due'), ('complete', 'Complete')], default='due', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_tasks', to='hub.department')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('department', 'month', 'task')},
            },
        ),
    ]
