# Generated by Django 6.0.7 on 2026-08-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_meeting_departments_departmentmonthlytask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitmentround',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='recruitmentround',
            name='time',
            field=models.CharField(blank=True, help_text='e.g. "11:00 AM"', max_length=30),
        ),
    ]
