# Generated by Django 6.0.7 on 2026-08-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_alter_recruitmentround_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayrollRecord',
        ),
    ]
