# Generated by Django 6.0.7 on 2026-08-07 06:45

from django.db import migrations, models


def delete_old_monthly_tasks(apps, schema_editor):
    """The old schema had one row per (department, month, task) — those
    rows don't map onto the new permanent-checklist schema, and keeping them
    would violate the new (department, task) unique constraint applied right
    after this runs. Safe to wipe: they were auto-regenerated scaffolding,
    not user-entered data worth preserving."""
    DepartmentMonthlyTask = apps.get_model('hub', 'DepartmentMonthlyTask')
    DepartmentMonthlyTask.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_delete_payrollrecord'),
    ]

    operations = [
        migrations.RunPython(delete_old_monthly_tasks, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['division__order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='departmentmonthlytask',
            options={'ordering': ['due_day', 'task']},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='departmentmonthlytask',
            unique_together={('department', 'task')},
        ),
        migrations.AddField(
            model_name='departmentmonthlytask',
            name='due_day',
            field=models.PositiveSmallIntegerField(default=28, help_text='Day of the month this is due (1-31).'),
        ),
        migrations.AddField(
            model_name='departmentmonthlytask',
            name='last_completed_month',
            field=models.DateField(blank=True, help_text='Set automatically to the 1st of the month it was last marked Complete.', null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Controls display order everywhere (lower = first).'),
        ),
        migrations.RemoveField(
            model_name='departmentmonthlytask',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='departmentmonthlytask',
            name='month',
        ),
        migrations.RemoveField(
            model_name='departmentmonthlytask',
            name='status',
        ),
    ]
