# Generated by Django 6.0.7 on 2026-08-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_set_division_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opening',
            options={'ordering': ['department__division__order', 'department__name']},
        ),
    ]
